spring:
  application:
    name: back
  datasource:
    url: jdbc:mysql://localhost:3306/altentestdb
    username: user
    password: userpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mysql:
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/altentestdb
      username: user
      password: userpassword
    hibernate:
      ddl-auto: update
      show-sql: true
  sql:
    init:
      platform: mysql

