version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql8-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: altentestdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
